# Generated by Django 4.1.2 on 2022-10-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_homework_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='Title',
            field=models.CharField(choices=[('LAB', 'LAB'), ('Assignment', 'Assignment'), ('Note', 'Note'), ('Notice', 'Notice')], max_length=15),
        ),
    ]
