# Generated by Django 4.1.2 on 2022-10-29 05:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_homework_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='Description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
